[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["StakePadV1", "RewardReceiver"]
tests = ["test/"]

[rpc_endpoints]
hoodi = "${HOODI_RPC}"
goerli = "${GOERLI_RPC}"
mainnet = "${MAINNET_RPC}"

[etherscan]
hoodi = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
